github_url: https://github.com/kpraveenkumar19
linkedin_url: https://www.linkedin.com/in/praveen~k
about_url: /about/
projects_url: /projects/
contact_url: /contact/
disclaimer_url: /disclaimer/
resume_url: /resume.pdf